=== bog1978/GraphLight/GraphLight.Core/Model/LGML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Graph">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="VertexCategory" type="VertexCategory" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="EdgeCategory" type="EdgeCategory" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Vertex" type="Vertex" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Edge" type="Edge" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="PK_EdgeCategory">
			<xs:selector xpath="EdgeCategory"/>
			<xs:field xpath="@Id"/>
		</xs:key>
		<xs:key name="PK_Vertex">
			<xs:selector xpath="Vertex"/>
			<xs:field xpath="@Id"/>
		</xs:key>
		<xs:key name="PK_VertexCategory">
			<xs:selector xpath="VertexCategory"/>
			<xs:field xpath="@Id"/>
		</xs:key>
		<xs:keyref name="FK_EdgeCategory" refer="PK_EdgeCategory">
			<xs:selector xpath="Edge"/>
			<xs:field xpath="@Category"/>
		</xs:keyref>
		<xs:keyref name="FK_EdgeDst" refer="PK_Vertex">
			<xs:selector xpath="Edge"/>
			<xs:field xpath="@Dst"/>
		</xs:keyref>
		<xs:keyref name="FK_EdgeSrc" refer="PK_Vertex">
			<xs:selector xpath="Edge"/>
			<xs:field xpath="@Src"/>
		</xs:keyref>
		<xs:keyref name="FK_VertexCategory" refer="PK_VertexCategory">
			<xs:selector xpath="Vertex"/>
			<xs:field xpath="@Category"/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="Edge">
		<xs:complexContent>
			<xs:extension base="Element">
				<xs:attribute name="Src" type="xs:string" use="required"/>
				<xs:attribute name="Dst" type="xs:string" use="required"/>
				<xs:attributeGroup ref="EdgeAttrs"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="EdgeCategory">
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attributeGroup ref="EdgeAttrs"/>
	</xs:complexType>
	<xs:complexType name="Element" abstract="true">
		<xs:attribute name="Category" type="xs:string" use="optional"/>
		<xs:attribute name="Label" type="xs:string" use="optional"/>
		<xs:attribute name="Stroke" type="Color" use="optional" default="Black"/>
		<xs:attribute name="StrokeThickness" type="xs:double" use="optional" default="1"/>
	</xs:complexType>
	<xs:complexType name="Vertex">
		<xs:complexContent>
			<xs:extension base="Element">
				<xs:attribute name="Id" type="xs:string" use="required"/>
				<xs:attributeGroup ref="VertexAttrs"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="VertexCategory">
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attributeGroup ref="VertexAttrs"/>
	</xs:complexType>
	<xs:simpleType name="Color">
		<xs:restriction base="xs:string">
			<xs:pattern value="#[\da-f]{6}|AliceBlue|AntiqueWhite|Aqua|Aquamarine|Azure|Beige|Bisque|Black|BlanchedAlmond|Blue|BlueViolet|Brown|BurlyWood|CadetBlue|Chartreuse|Chocolate|Coral|CornflowerBlue|Cornsilk|Crimson|Cyan|DarkBlue|DarkCyan|DarkGoldenrod|DarkGray|DarkGreen|DarkKhaki|DarkMagenta|DarkOliveGreen|DarkOrange|DarkOrchid|DarkRed|DarkSalmon|DarkSeaGreen|DarkSlateBlue|DarkSlateGray|DarkTurquoise|DarkViolet|DeepPink|DeepSkyBlue|DimGray|DodgerBlue|Firebrick|FloralWhite|ForestGreen|Fuchsia|Gainsboro|GhostWhite|Gold|Goldenrod|Gray|Green|GreenYellow|Honeydew|HotPink|IndianRed|Indigo|Ivory|Khaki|Lavender|LavenderBlush|LawnGreen|LemonChiffon|LightBlue|LightCoral|LightCyan|LightGoldenrodYellow|LightGray|LightGreen|LightPink|LightSalmon|LightSeaGreen|LightSkyBlue|LightSlateGray|LightSteelBlue|LightYellow|Lime|LimeGreen|Linen|Magenta|Maroon|MediumAquamarine|MediumBlue|MediumOrchid|MediumPurple|MediumSeaGreen|MediumSlateBlue|MediumSpringGreen|MediumTurquoise|MediumVioletRed|MidnightBlue|MintCream|MistyRose|Moccasin|NavajoWhite|Navy|OldLace|Olive|OliveDrab|Orange|OrangeRed|Orchid|PaleGoldenrod|PaleGreen|PaleTurquoise|PaleVioletRed|PapayaWhip|PeachPuff|Peru|Pink|Plum|PowderBlue|Purple|Red|RosyBrown|RoyalBlue|SaddleBrown|Salmon|SandyBrown|SeaGreen|SeaShell|Sienna|Silver|SkyBlue|SlateBlue|SlateGray|Snow|SpringGreen|SteelBlue|Tan|Teal|Thistle|Tomato|Transparent|Turquoise|Violet|Wheat|White|WhiteSmoke|Yellow|YellowGreen"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VertexShape">
		<xs:restriction base="xs:string">
			<xs:enumeration value="None"/>
			<xs:enumeration value="Ellipse"/>
			<xs:enumeration value="Rectangle"/>
			<xs:enumeration value="Diamond"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="EdgeAttrs">
		<xs:attribute name="Weight" type="xs:double" use="optional" default="1"/>
		<xs:attribute name="Style" type="EdgeStyle" use="optional" default="Solid"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="VertexAttrs">
		<xs:attribute name="Background" type="Color" use="optional" default="LightGray"/>
		<xs:attribute name="Foreground" type="Color" use="optional" default="Black"/>
		<xs:attribute name="Shape" type="VertexShape" use="optional" default="Ellipse"/>
	</xs:attributeGroup>
	<xs:simpleType name="EdgeStyle">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Solid"/>
			<xs:enumeration value="Dashed"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== bog1978/GraphLight/GraphLight.Demo.Wpf/Examples/Sample.xml
<Graph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../GraphLight.Core/Model/LGML/LGML.xsd">
	<VertexCategory Id="process" Shape="Rectangle" Foreground="Black" Background="LightGray" Margin="10" FontSize="18"/>
	<VertexCategory Id="gateway" Shape="Diamond" Foreground="Green" Background="White" FontSize="25"/>
	<VertexCategory Id="initial" Shape="Ellipse" Foreground="White" Background="Green"/>
	<VertexCategory Id="final" Shape="Ellipse" Foreground="White" Background="Red"/>
	<EdgeCategory Id="normal" Weight="1" Stroke="Green" StrokeThickness="3" StrokeStyle="DashDot"/>
	<EdgeCategory Id="conditional" Weight="1" StrokeStyle="Dash" Stroke="Gray" StrokeThickness="1" Foreground="Blue"/>
	<Vertex Id="start" Category="initial" FontSize="18" StrokeStyle="Solid"/>
	<Vertex Id="end" Category="final" FontSize="18" StrokeStyle="Dash"/>
	<Vertex Id="switch" Category="gateway" StrokeStyle="DashDot"/>
	<Vertex Id="service1" Category="process" StrokeStyle="Dot"/>
	<Vertex Id="service2" Category="process" StrokeStyle="Dot"/>
	<Edge Src="start" Dst="switch" Category="normal"/>
	<Edge Src="switch" Dst="service1" Category="conditional" Label="Yes"/>
	<Edge Src="switch" Dst="service2" Category="conditional" Label="No"/>
	<Edge Src="service1" Dst="end" Category="normal"/>
	<Edge Src="service2" Dst="end" Category="normal"/>
</Graph>
