=== bog1978/GraphLight/GraphLight.Core/Model/LGML/LGML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 rel. 2 sp1 (x64) (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Graph" type="LgmlGraph">
		<xs:key name="PK_EdgeCategory">
			<xs:selector xpath="EdgeCategory"/>
			<xs:field xpath="@Id"/>
		</xs:key>
		<xs:key name="PK_Vertex">
			<xs:selector xpath="Vertex"/>
			<xs:field xpath="@Id"/>
		</xs:key>
		<xs:key name="PK_VertexCategory">
			<xs:selector xpath="VertexCategory"/>
			<xs:field xpath="@Id"/>
		</xs:key>
		<xs:keyref name="FK_EdgeCategory" refer="PK_EdgeCategory">
			<xs:selector xpath="Edge"/>
			<xs:field xpath="@Category"/>
		</xs:keyref>
		<xs:keyref name="FK_EdgeDst" refer="PK_Vertex">
			<xs:selector xpath="Edge"/>
			<xs:field xpath="@Dst"/>
		</xs:keyref>
		<xs:keyref name="FK_EdgeSrc" refer="PK_Vertex">
			<xs:selector xpath="Edge"/>
			<xs:field xpath="@Src"/>
		</xs:keyref>
		<xs:keyref name="FK_VertexCategory" refer="PK_VertexCategory">
			<xs:selector xpath="Vertex"/>
			<xs:field xpath="@Category"/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="LgmlEdge">
		<xs:complexContent>
			<xs:extension base="LgmlElement">
				<xs:attribute name="Src" type="xs:string" use="required"/>
				<xs:attribute name="Dst" type="xs:string" use="required"/>
				<xs:attributeGroup ref="EdgeAttrs"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="LgmlEdgeCategory">
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attributeGroup ref="CommonAttrs"/>
		<xs:attributeGroup ref="EdgeAttrs"/>
	</xs:complexType>
	<xs:complexType name="LgmlElement" abstract="true">
		<xs:attribute name="Category" type="xs:string" use="optional"/>
		<xs:attribute name="Label" type="xs:string" use="optional"/>
		<xs:attributeGroup ref="CommonAttrs"/>
	</xs:complexType>
	<xs:complexType name="LgmlGraph">
		<xs:sequence>
			<xs:element name="VertexCategory" type="LgmlVertexCategory" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="EdgeCategory" type="LgmlEdgeCategory" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Vertex" type="LgmlVertex" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Edge" type="LgmlEdge" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LgmlVertex">
		<xs:complexContent>
			<xs:extension base="LgmlElement">
				<xs:attribute name="Id" type="xs:string" use="required"/>
				<xs:attributeGroup ref="VertexAttrs"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="LgmlVertexCategory">
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attributeGroup ref="CommonAttrs"/>
		<xs:attributeGroup ref="VertexAttrs"/>
	</xs:complexType>
	<xs:simpleType name="LgmlColor">
		<xs:restriction base="xs:string">
			<xs:pattern value="#[\da-f]{6}|AliceBlue|AntiqueWhite|Aqua|Aquamarine|Azure|Beige|Bisque|Black|BlanchedAlmond|Blue|BlueViolet|Brown|BurlyWood|CadetBlue|Chartreuse|Chocolate|Coral|CornflowerBlue|Cornsilk|Crimson|Cyan|DarkBlue|DarkCyan|DarkGoldenrod|DarkGray|DarkGreen|DarkKhaki|DarkMagenta|DarkOliveGreen|DarkOrange|DarkOrchid|DarkRed|DarkSalmon|DarkSeaGreen|DarkSlateBlue|DarkSlateGray|DarkTurquoise|DarkViolet|DeepPink|DeepSkyBlue|DimGray|DodgerBlue|Firebrick|FloralWhite|ForestGreen|Fuchsia|Gainsboro|GhostWhite|Gold|Goldenrod|Gray|Green|GreenYellow|Honeydew|HotPink|IndianRed|Indigo|Ivory|Khaki|Lavender|LavenderBlush|LawnGreen|LemonChiffon|LightBlue|LightCoral|LightCyan|LightGoldenrodYellow|LightGray|LightGreen|LightPink|LightSalmon|LightSeaGreen|LightSkyBlue|LightSlateGray|LightSteelBlue|LightYellow|Lime|LimeGreen|Linen|Magenta|Maroon|MediumAquamarine|MediumBlue|MediumOrchid|MediumPurple|MediumSeaGreen|MediumSlateBlue|MediumSpringGreen|MediumTurquoise|MediumVioletRed|MidnightBlue|MintCream|MistyRose|Moccasin|NavajoWhite|Navy|OldLace|Olive|OliveDrab|Orange|OrangeRed|Orchid|PaleGoldenrod|PaleGreen|PaleTurquoise|PaleVioletRed|PapayaWhip|PeachPuff|Peru|Pink|Plum|PowderBlue|Purple|Red|RosyBrown|RoyalBlue|SaddleBrown|Salmon|SandyBrown|SeaGreen|SeaShell|Sienna|Silver|SkyBlue|SlateBlue|SlateGray|Snow|SpringGreen|SteelBlue|Tan|Teal|Thistle|Tomato|Transparent|Turquoise|Violet|Wheat|White|WhiteSmoke|Yellow|YellowGreen"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LgmlEdgeStyle">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Solid"/>
			<xs:enumeration value="Dashed"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LgmlVertexShape">
		<xs:restriction base="xs:string">
			<xs:enumeration value="None"/>
			<xs:enumeration value="Ellipse"/>
			<xs:enumeration value="Rectangle"/>
			<xs:enumeration value="Diamond"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="CommonAttrs">
		<xs:attribute name="Stroke" type="LgmlColor" use="optional"/>
		<xs:attribute name="StrokeThickness" type="xs:double" use="optional"/>
		<xs:attribute name="FontSize" type="xs:double" use="optional"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="EdgeAttrs">
		<xs:attribute name="Weight" type="xs:double" use="optional"/>
		<xs:attribute name="Style" type="LgmlEdgeStyle" use="optional"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="VertexAttrs">
		<xs:attribute name="Background" type="LgmlColor" use="optional"/>
		<xs:attribute name="Foreground" type="LgmlColor" use="optional"/>
		<xs:attribute name="Shape" type="LgmlVertexShape" use="optional"/>
		<xs:attribute name="Margin" type="xs:double" use="optional"/>
	</xs:attributeGroup>
</xs:schema>

=== bog1978/GraphLight/GraphLight.Core/Model/LGML/Sample.xml
<Graph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LGML.xsd">
	<VertexCategory Id="process" Shape="Rectangle" Foreground="Black" Background="LightGray"/>
	<VertexCategory Id="gateway" Shape="Diamond" Foreground="Green" Background="White"/>
	<VertexCategory Id="initial" Shape="Ellipse" Foreground="White" Background="Green"/>
	<VertexCategory Id="final" Shape="Ellipse" Foreground="White" Background="Red"/>
	<EdgeCategory Id="normal" Weight="1" Style="Solid"/>
	<EdgeCategory Id="conditional" Weight="1" Style="Dashed"/>
	<Vertex Id="start" Category="initial"/>
	<Vertex Id="end" Category="final"/>
	<Vertex Id="switch" Category="gateway"/>
	<Vertex Id="service1" Category="process"/>
	<Vertex Id="service2" Category="process"/>
	<Edge Src="start" Dst="switch" Category="normal"/>
	<Edge Src="switch" Dst="service1" Category="conditional"/>
	<Edge Src="switch" Dst="service2" Category="conditional"/>
	<Edge Src="service1" Dst="end" Category="normal"/>
	<Edge Src="service2" Dst="end" Category="normal"/>
</Graph>
